# Generated by Django 4.2 on 2023-04-29 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0002_rename_bullets_board_rename_bulletcomment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bullets',
            new_name='board',
        ),
    ]
